### ISSUE TITLE
Compiling for win server 2019 or win10 #3

### ISSUE THREAD

**Issue by n0whereman** [Kharos102/IOCTLDump#3]
Hello,

have you really tried to use it on win server 2019 or win10 ? The SDK is missing also the function ExAllocatePool2(...), which you have not defined.
I've wrapped it accordingly as such: 
```
PVOID ExAllocatePool2(POOL_TYPE type, SIZE_T nameLen, ULONG tag) {
    return ExAllocatePoolWithTag(type, nameLen, tag);
}
```
and defined the 
`#define POOL_FLAG_NON_PAGED        (POOL_TYPE)       0x0000000000000040UI64` 

Eventually I got it running as a service and as soon as I issued any connect to any of devices wit IOCTLDumpCLient.exe, the system crashed (kernel panic) giving me a memdump due to a violation. Is this due to my improper changes or there might be other bug as well..

**Comment by Kharos102** [comment]
Hi,

Yes, the readme in this repo states `To target Windows 10, ensure you have 'W10' defined in your visual studio preprocessor definitions.`.

If you don't want to use visual studio's preprocessor to enable `W10` for the build, simply add the line `#define W10` to the top of the driver source file.

Though it appears you're saying that's not sufficient, which has not been my experience with the win10 sdk. Can you please provide the specific sdk version you're using?

**Comment by Kharos102** [comment]
Perhaps you're using an even older win10 sdk, as ExAllocatePool2 is supported from Windows 10, version 2004 as described on msdn https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exallocatepool2

I suggest using at least that version win10 sdk if your target supports it.

**Comment by n0whereman** [comment]
Yes, its earlier version than 2004 of win10/win server 2019, that's why I (re)defined the function as mentioned in the first comment. It worked, however, it crashed badly, so I wanted to know if you happen to have any idea about either my wrapper or as to what could cause the crash.

**Comment by Kharos102** [comment]
Your wrapper looks incorrect.

For example, it looks like you're defining `POOL_FLAG_NON_PAGED` as `0x40` because that's the value of it when passed into `ExAllocatePool2`, however this is incompatible with `ExAllocatePoolWithTag`, the `ExAllocatePoolWithTag` API does not take the same `type` parameter as `ExAllocatePool2`, read the doc: https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exallocatepoolwithtag

It takes `POOL_TYPE` (instead of `POOL_FLAGS` that ExAllocatePool2 takes), for non-paged pool it would be the value `0` instead of `0x40`.

That's an initial observation.

**Comment by n0whereman** [comment]
Will give it a try, thanks.

**Comment by binaryhouse** [comment]
It works with the 0x0. I can make a PR  if you want me to, in order to add compatibility for versions below 2004. Thanks

**Comment by n0whereman** [comment]
It works with the zero! I can make a PR for adding compatibility with versions below 2004 if you want me to. Thanks

**Comment by Kharos102** [comment]
Sure!
